//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleCalendarSchedule
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassSchedule()
        {
            this.Events = new HashSet<Event>();
        }
    
        public int Id { get; set; }
        public string ClassName { get; set; }
        public System.TimeSpan A { get; set; }
        public System.TimeSpan B { get; set; }
        public System.TimeSpan C { get; set; }
        public System.TimeSpan D { get; set; }
        public System.TimeSpan E { get; set; }
        public System.TimeSpan F { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Event> Events { get; set; }
    }
}
