//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleCalendarSchedule
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScheduleDatabaseEntities : DbContext
    {
        public ScheduleDatabaseEntities()
            : base("name=ScheduleDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassSchedule> ClassSchedules { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Table> Tables { get; set; }
    }
}
